version: '2'
services:
  web:
    build: .
    command: bundle exec rake
    volumes:
      - .:/usr/src/app
    volumes_from:
      - bundle

  bundle:
    image: busybox
    volumes:
      - /bundle
